name: Build and Test
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install pylint pytest
          pip install -r requirements.txt
      - name: Lint with pylint
        run: |
          pylint **/*.py --exit-zero --output-format=colorized
      - name: Test with unittest
        run: |
          python -m unittest discover -s tests
