name: deploy model

on:
  workflow_run:
    workflows: [ "train model" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and tag docker image
        run: |
          docker build -t mahmoudalbardan/fraudapp:latest .
          docker tag mahmoudalbardan/fraudapp:latest mahmoudalbardan/fraudapp:${{github.sha}}

      - name: push built image to docker hub
        run: |
          docker push mahmoudalbardan/fraudapp:latest
          docker push mahmoudalbardan/fraudapp:${{github.sha}}

      - name: deploy gcp to vm
        run: |
          echo "ssh to a gcp compute engine then pull docker image from dockerhub and run it .. it will not complete the workflow"
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | base64 --decode > gcpkey.json
          gcloud auth activate-service-account --key-file=gcpkey.json
          gcloud config set project XXXX
          gcloud compute ssh XXXXX@XXXX docker pull mahmoudalbardan/fraudapp:latest
          gcloud compute ssh XXXXX@XXXX docker run mahmoudalbardan/fraudapp:latest
