name: deploy model

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: build and tag docker image
        run: |
          docker build -t mahmoudalbardan/fraudapp:latest .
          docker tag mahmoudalbardan/fraudapp:latest mahmoudalbardan/fraudapp:${{github.sha}}

      - name: push built image to docker hub
        run: |
          docker push mahmoudalbardan/fraudapp:latest
          docker push mahmoudalbardan/fraudapp:${{github.sha}}

      - name: deploy on server
        run: |
          echo "ssh to a server then pull docker image from dockerhub and run it .. it will not complete the workflow"
          ssh mab@blablablaserver docker pull mahmoudalbardan/fraudapp:latest
          ssh mab@blablablaserver docker run mahmoudalbardan/fraudapp:latest
