name: Model Training

on:
  push:
    branches: [ "train" ]  # Trigger on pushes to 'train' branch
  workflow_dispatch:  # Manual trigger

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: training the model
        run: |
          python train_model.py