name: Model Training

on:
  workflow_dispatch:
    inputs:
      training_branch:
        description: "Branch to trigger training"
        required: true
        default: "training"

jobs:
  train_model:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.training_branch }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Train model
        run: |
          python main.py --train
          

      - name: Save model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: models/saved_model/
