name: Monitor and Retrain

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight

jobs:
  monitor_and_retrain:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download deployed model
        uses: actions/download-artifact@v3
        with:
          name: deployed-model
          path: models/saved_model/
      - name: Monitor performance
        run: |
          python main.py --monitor --model-path models/saved_model/
      - name: Retrain model if
